version: "3.3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000" # change this to alter output port
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
      - migrate
      - particles
    links:
      - "db"
      - "db:database"
  migrate:
    build: .
   # command: python manage.py migrate
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
  particles:
    build: .
    command: python HISKPScreen/particle_manager.py
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
      